from typing import Annotated, Optional, TypedDict
from langchain_core.messages import BaseMessage
from langgraph.graph.message import add_messages

from src.features.formations.schema import FormationStructureCreate


class State(TypedDict):
    messages: Annotated[list[BaseMessage], add_messages]
    
    # The ID of the formation being edited
    formation_id: int
    
    # The user's prompt (e.g., "change the title of the first lesson")
    user_prompt: str
    
    # The current structure of the course, fetched from the DB
    current_structure: Optional[FormationStructureCreate]
    
    # The new structure of the course, as proposed by the agent
    proposed_structure: Optional[FormationStructureCreate]
    
    # The diff generated by difftastic between the current and proposed structures
    diff: Optional[str]

    
    
    
